exports.PUB_TOPIC = {NEW: "NEW", UPDATE: "UPDATE"}

exports.FOLLOW_TYPE = {ITEM: "ITEM", USER: "USER", KEYWORD: "KEYWORD"};

exports.MAX_SUBMITTED_COUNT = 100;

exports.CRAWL_NEW_INTERVAL = 60;
exports.CHECK_CHANGE_INTERVAL = 10;